---
title: "Deepflow"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
library(kerasR)
library(largeVis)
library(DT)
library(DBI)
library(RSQLite)
library(deepflow)
library(ggplot2)
library(data.table)

options(shiny.maxRequestSize=600*1024^2) 
sqlitePath <- "~/.deepflow/deepflow.db"
gates = vector()

# Retrieve existing table names
db <- dbConnect(RSQLite::SQLite(), sqlitePath)

parameters <- reactiveValues(data=NULL,
			     selection=NULL,
			     coordinates=NULL,
			     files=NULL)

jet.colors <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan", "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))


filenames <- dbListTables(db)
parameters$files <-  data.frame(File=filenames)
dbDisconnect(db)
```

Visualisations
=======================================================================


Column {data-width=250}
-----------------------------------------------------------------------
### My Files
```{r}
DT::dataTableOutput("filelist")
output$filelist <- renderDataTable({
	datatable(parameters$files, options = list(bPaginate = FALSE,
					scrollY = "200px"),
		 selection=list(mode="single", target="row"), 
		 rownames = FALSE)
}, server=FALSE, selection="single")

observeEvent(input$filelist_rows_selected,
	     {
		withProgress({
			ix <- input$filelist_rows_selected
			fcs <- pull_fcs(as.character(parameters$files$File[ix]), sqlitePath)
	     		gates <- colnames(fcs)
			parameters$data <- data.matrix(fcs)
			if (input$asinhTransform){
				parameters$data <- asinh(data.matrix(fcs)/5)
			}
			
			db <- dbConnect(RSQLite::SQLite(), sqlitePath)
	     		exists <- dbExistsTable(db, paste0(as.character(parameters$files$File[ix]), "_coordinates"))
	     		if(exists){
		     		parameters$coordinates <- dbReadTable(db, paste0(as.character(parameters$files$File[ix]), "_coordinates"))
		     		parameters$selection <- dbReadTable(db, paste0(as.character(parameters$files$File[ix]), "_gates"))[,1]
		     		updateSelectizeInput(session, 'visualiseGates', choices=parameters$selection)
	     		}
	     		dbDisconnect(db)

		}, message="Retrieving gate information.")

	     	updateSelectizeInput(session, 'gateSelect', choices=gates)})
```

### Run

```{r}

# Elements
selectInput("gateSelect", "Select Gates", gates, multiple=TRUE, selectize=FALSE, width="100%", size=8)
checkboxInput("asinhTransform", label = "Apply hyperbolic arcsin transformation", value = TRUE)
actionButton("run", "Analyse", width = "100%")


# Listeners
observeEvent(input$gateSelect, {parameters$selection <- input$gateSelect})

observeEvent(input$run, {

		     withProgress({
		     	ix <- input$filelist_rows_selected
			fcs <- pull_fcs(as.character(parameters$files$File[ix]), sqlitePath)

	     		parameters$data <- data.matrix(fcs)
			if (input$asinhTransform){
				print(input$asinhTransform)
				parameters$data <- asinh(data.matrix(fcs)/5)
			}
	     		}, message="Retrieving dataset...")

		     
		     updateSelectizeInput(session, 'visualiseGates', choices=parameters$selection) 
		      autoencode()
})

```

Column {.tabset data-width=500}
-----------------------------------------------------------------------
### Scatter

```{r}

# Elements
renderPlot({
	tryCatch({
		if (is.null(parameters$coordinates)){	
			return()
		}  else {	
			selected_gate_value <- parameters$data[,input$visualiseGates]	
		
			withProgress({p <- ggplot(parameters$coordinates,
			    	aes(Deep1, Deep2, col=selected_gate_value)) + geom_point(size=0.75) +
	   			scale_colour_gradientn(colours = jet.colors(7)) +
				theme_void() + 
				theme(legend.title=element_blank())
				print(p)
				}, message = "Loading graph...")
		}
		}, error = function(err){
			print("Trying load your graph...")
	}
	)
})

# Listeners

autoencode <- eventReactive(input$run, {
	withProgress(message = 'Learning...this may take a while', value=0, max=4, {
		ix <- input$filelist_rows_selected
		fcs <- parameters$data

		X <- fcs[, parameters$selection]	
		incProgress(1, detail = "Running autoencoder.")
		a <- autoencoder(X)
		yh <- as.data.frame(keras_predict(a$encoder, scale(X)))
		tX <- t(yh)

		incProgress(1, detail = "Estimating embeddings.")
		set.seed(1234)
		v <- largeVis(tX, threads=parallel::detectCores(), verbose=TRUE, seed=123)
		xy <- t(v$coords)
		coordinates <- data.frame(Deep1=xy[,1], Deep2=xy[,2])
		parameters$coordinates <- coordinates

		incProgress(1, detail = "Saving results to database.")
		db <- dbConnect(RSQLite::SQLite(), sqlitePath)
		dbWriteTable(db,
			     paste0(parameters$files$File[input$filelist_rows_selected], "_coordinates"),
			     coordinates, overwrite=TRUE)
		dbWriteTable(db,
			     paste0(parameters$files$File[input$filelist_rows_selected], "_gates"),
			     data.frame(Gates = parameters$selection), overwrite=TRUE)	

		dbDisconnect(db)
})
	coordinates
})

```

### Density

```{r}
# Elements
renderPlot({
	tryCatch({
		if (is.null(parameters$coordinates)){	
			return()
		}  else {		

			withProgress({p <- ggplot(parameters$coordinates,
			    	aes(Deep1, Deep2)) +
				stat_density2d(aes(alpha=..level.., fill=..level..),
					       size=2, bins=10, geom="polygon") + 
	   			scale_fill_gradient(low = "yellow", high = "red") + 
				scale_alpha(range = c(0.00, 0.5), guide = FALSE) +
				geom_density2d(colour="black") +

				theme_void() + 
				theme(legend.title=element_blank())
				print(p)
				}, message = "Loading graph...")
		}
		}, error = function(err){
			print("Attempting to load your graph...")
	}
	)
})


```

Column {data-width=250}
-----------------------------------------------------------------------
### Gates
```{r}
selectInput("visualiseGates", "Visualise Gates", gates, selected=NULL,
	    multiple=FALSE, width="100%", selectize=TRUE)


```

### Actions

```{r}

actionLink("saveImage", "⎙ Save Image")

```

My Datasets
=======================================================================

Column {data-width=600}
-----------------------------------------------------------------------
### All files
```{r}
DT::dataTableOutput("dbList")

output$dbList <- renderDataTable({datatable(parameters$files, options = list(bPaginate=FALSE, scrollY = "200"),
				selection=list(mode="single", target="row"),
				rownames=FALSE)}, server=FALSE)

observeEvent(input$dbList_rows_selected,{
		     print(input$dbList_rows_selected)

})


```

###
```{r}
actionLink("deleteFiles", "x Remove all selected Files")


observeEvent(input$deleteFiles,{
		     withProgress({
		     ix <- input$dbList_rows_selected
		     files_to_remove <- as.character(parameters$files$File[ix])
		     db <- dbConnect(RSQLite::SQLite(), sqlitePath)
		     dbRemoveTable(db, files_to_remove)
		     filenames <- dbListTables(db)
		     parameters$files <-  data.frame(File=filenames)

		     dbDisconnect(db)
		     },
		     message = "Removing dataset...") 
})

```

 Column {data-width=250}
----------------------------------------------------------------------
### Upload file

```{r}
fileInput("fileUpload", label = h4("Upload local flow cytometry datasets"))

observeEvent(input$fileUpload, {
	withProgress({	
	inFile <- input$fileUpload
	if (is.null(inFile))
		return(NULL)
	fcs <- fread(inFile$datapath)
	fcs <- as.data.frame(unclass(fcs))
	keep <- sapply(fcs, class) %in% c("numeric", "integer")
	fcs <- fcs[,keep]

	model <- isofor::iForest(fcs, 100, max(10, round(0.005 * nrow(fcs))))
	yh <- predict(model, fcs, n.cores=parallel::detectCores())
	keep <- yh < quantile(yh, 0.95, na.rm=TRUE)
	fcs <- fcs[keep,]

	db <- dbConnect(RSQLite::SQLite(), sqlitePath)
	dbWriteTable(db, inFile$name, fcs, overwrite=TRUE)

	filenames <- dbListTables(db)
	parameters$files <-  data.frame(File=filenames)
	dbDisconnect(db)}, message= "Importing dataset...")
})
```


Help
=======================================================================



