# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

proximity_matrix <- function(idx) {
    .Call('_cytorf_proximity_matrix', PACKAGE = 'cytorf', idx)
}

